# 로그아웃
GET http://localhost:8080/v1/api/user/logout
Content-Type: application/json;charset=UTF-8
Authorization: bearer eyJyZWdEYXRlIjoxNjI4NzY3OTkxNTQ5LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibmFtZSI6IuuwleykgOyYgSIsImVtYWlsIjoiY29vaW5ncG9wQGdtYWlsLmNvbSIsImlhdCI6MTYyODc2Nzk5MSwiZXhwIjoxNjI4NzcxNTkxfQ.vZLxhOWjFwNNGOtavei3Z55Yo2cqqv7l8WCOvl_skpA