spring:
  application:
    name: api-client
  profiles:
    active: local
  port: 8080
  shutdown: graceful
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: ENC(3Axq03mjDNDTYk8GtS/nApWJiXXzy3SV)
    password: ENC(inKWo0++SlCqf4kewyjcbTPha1pPuopD)
    max-active: 4
    max-idle: 4
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: com.cooingpop.apiclient.config.MySQLCustomDialect

logging:
  level:
    root: DEBUG

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
# 서버 실행시 VM OPTIONS 사용 -Djasypt.encryptor.password=cooingpop

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

api:
  version: '@project.version@'
  url: 'http://127.0.0.1:${spring.port}'
