# 단일 회원 검색
GET http://localhost:8080/v1/api/user
Content-Type: application/json;charset=UTF-8
Authorization: bearer eyJyZWdEYXRlIjoxNjI4NzQ4NzA5NTY2LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibmFtZSI6IuuwleykgOyYgSIsImVtYWlsIjoiY29vaW5ncG9wQGdtYWlsLmNvbSIsImlhdCI6MTYyODc0ODcwOSwiZXhwIjoxNjI4NzUyMzA5fQ.1vAc87ytOsvogYxN7DTkZXgbpK7JIThbR-7sDEjKJow

{
  "email": "cooingpo2p@gmail.com"
}