# 여러 회원 목록 조회
GET http://localhost:8080/v1/api/users
Content-Type: application/json;charset=UTF-8
Authorization: bearer eyJyZWdEYXRlIjoxNjI4NzQ4NzA5NTY2LCJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwibmFtZSI6IuuwleykgOyYgSIsImVtYWlsIjoiY29vaW5ncG9wQGdtYWlsLmNvbSIsImlhdCI6MTYyODc0ODcwOSwiZXhwIjoxNjI4NzUyMzA5fQ.1vAc87ytOsvogYxN7DTkZXgbpK7JIThbR-7sDEjKJow

{
  "email": "cooingpop@gmail.com",
  "name": "박준영"
}